<?php
// Scheduled reorder-reminder mailer.
//
// Run from cPanel → Cron Jobs (or any scheduler) on whatever cadence you like:
//
//   /usr/local/bin/php /home/you/public_html/cron_reorder_alerts.php
//
// It recomputes the Order Report's reorder alerts (using the same code the page
// uses, in reports/order_report/report_lib.php), keeps only those that are
// currently triggered AND have their "Email" box ticked, and emails a single
// digest to the administrator address (Settings → Email Notifications).
//
// To avoid spamming on a frequent schedule, each alert is re-sent at most once
// per OP_ALERT_EMAIL_MIN_HOURS (tracked in alerts.last_triggered).
//
// Auth: when run from the command line (the normal cron case) it just runs.
// When requested over HTTP it requires an admin login, so the endpoint can't be
// abused to send mail anonymously.

require_once __DIR__ . '/common.php';

if (PHP_SAPI !== 'cli') {
    // Browser/wget invocation must be an authenticated admin.
    require_once __DIR__ . '/auth.php';
    requireLogin();
}

require_once __DIR__ . '/mailer.php';
require_once __DIR__ . '/reports/order_report/report_lib.php';

$isCli = (PHP_SAPI === 'cli');
$log = function (string $line) use ($isCli) {
    if ($isCli) { fwrite(STDOUT, $line . "\n"); }
    else        { echo htmlspecialchars($line) . "<br>\n"; }
};

$db = getDB();

$adminEmail = trim((string)(setting('admin_email', '') ?? ''));
if ($adminEmail === '') {
    $log('No administrator email configured (Settings → Email Notifications). Nothing sent.');
    exit(0);
}

// Mirror the report's saved display options for stock/event handling so the
// emailed numbers match the page. Produce/Purchased view filters are NOT
// applied — reminders should fire for any enabled + email-flagged alert.
$rows = op_report_rows($db, [
    'ignore_stock'   => (setting('report_ignore_stock',  '0') === '1'),
    'ignore_events'  => (setting('report_ignore_events', '1') === '1'),
    'produce_only'   => false,
    'purchased_only' => false,
]);

// Triggered alerts that have the Email box ticked.
$alerts = op_report_alerts($db, $rows, true);
if (!$alerts) {
    $log('No email-enabled reorder alerts are currently triggered. Nothing to send.');
    exit(0);
}

// Skip any alert emailed within the cool-down window.
$now      = new DateTimeImmutable('now');
$cooldown = OP_ALERT_EMAIL_MIN_HOURS * 3600;
$toSend   = [];
$skipped  = 0;
foreach ($alerts as $a) {
    $last = $a['last_triggered'] ? strtotime((string)$a['last_triggered']) : false;
    if ($last !== false && ($now->getTimestamp() - $last) < $cooldown) {
        $skipped++;
        continue;
    }
    $toSend[] = $a;
}

if (!$toSend) {
    $log("All {$skipped} triggered alert(s) are within the "
        . OP_ALERT_EMAIL_MIN_HOURS . "h cool-down. Nothing to send.");
    exit(0);
}

// Build and send one digest.
$pantry  = trim((string)(setting('food_pantry_name', '') ?? ''));
$subject = ($pantry !== '' ? $pantry . ' — ' : '') . 'Reorder reminder'
         . (count($toSend) === 1 ? '' : 's') . ' (' . count($toSend) . ')';

$lines = [];
$lines[] = ($pantry !== '' ? $pantry . ' reorder reminders' : 'Reorder reminders') . ':';
$lines[] = '';
foreach ($toSend as $a) {
    $lines[] = '  • ' . $a['text'];
}
$lines[] = '';
$lines[] = 'Generated by OpenPantry on ' . now() . '.';
$body = implode("\n", $lines) . "\n";

$res = op_send_mail($adminEmail, $subject, $body);
if (!$res['ok']) {
    $log('Email send FAILED: ' . $res['error']);
    exit(1);
}

// Stamp last_triggered so the cool-down applies to what we just sent.
$upd = $db->prepare("UPDATE alerts SET last_triggered = ? WHERE id = ?");
$stamp = now();
foreach ($toSend as $a) {
    $upd->execute([$stamp, $a['id']]);
}

$log('Sent reorder reminder for ' . count($toSend) . ' item(s) to ' . $adminEmail
    . ($skipped ? " ({$skipped} skipped for cool-down)." : '.'));
exit(0);
